
#spring.jpa.properties.hibernate.default_batch_fetch_size=20
spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
    datasource:
        url: jdbc:postgresql://localhost:5433/library
        username: cuba
        password: cuba
        driverClassName: org.postgresql.Driver
