CREATE TABLE books
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    author      VARCHAR(255),
    description VARCHAR(255),
    publisher   VARCHAR(255),
    isbn        VARCHAR(255),
    year        INTEGER,
    CONSTRAINT pk_books PRIMARY KEY (id)
);